### ISSUE TITLE
Update rugged to avoid segmentation fault

### ISSUE THREAD

**Issue by aiionx** [gitlabhq/gitlab_git#58]
Could you please update rugged so it includes this commit?
https://github.com/libgit2/rugged/commit/0f8db3c453fe2cf8e6a820de1630f1b6492b8ca5

Thanks

**Comment by aiionx** [comment]
Before applying that patch sidekiq was being killed by the SEGV.
Since the error was not being handled.

After the patch all goes fine.

**Comment by randx** [comment]
Can you submit a Pull Request with update?

**Comment by aiionx** [comment]
That patch is currently only in rugged pre-releases. 
I will do the Pull Request once a stable version is released.

**Comment by jvanbaarsen** [comment]
Looks like this problem also occurs when you're trying to run `rake dev:seed`.

Attached is the stacktrace of the segfault:

https://gist.github.com/jvanbaarsen/19ba9a166b506e1f5c15
